// ============================================================
// TOEIC スタディブック — レベル別オリジナル問題バンク
// part2: 応答問題(音声) / part5: 短文穴埋め / part7: 長文読解
// answer: 正解インデックス(0始まり) / ja: 日本語訳
// choiceNotes: 各選択肢への補足(正解の根拠・誤答の理由)
// ============================================================

const QUESTIONS = {
  // ---------------- Lv1 基礎(目標400) ----------------
  1: {
    part2: [
      {
        q: "Where is the meeting room?",
        ja: "会議室はどこですか?",
        choices: ["It's on the second floor.", "At three o'clock.", "Yes, I do."],
        choiceNotes: [
          "「2階です」— 場所を答えているので正解",
          "「3時です」— 時刻の答え。WhenならOK",
          "「はい、そうします」— Where疑問文にYes/Noでは答えられない",
        ],
        answer: 0,
        exp: "Where(どこ)と場所を聞かれているので、場所を答えている (A) が正解です。",
      },
      {
        q: "When does the store open?",
        ja: "お店は何時に開きますか?",
        choices: ["It's near the station.", "At nine in the morning.", "Two coffees, please."],
        choiceNotes: [
          "「駅の近くです」— 場所の答え。WhereならOK",
          "「朝9時です」— 時刻を答えているので正解",
          "「コーヒーを2つください」— 注文の表現で無関係",
        ],
        answer: 1,
        exp: "When(いつ)と時を聞かれているので、時刻を答える (B) が正解です。",
      },
      {
        q: "Who is your manager?",
        ja: "あなたの上司は誰ですか?",
        choices: ["Ms. Brown is.", "In the office.", "On Monday."],
        choiceNotes: [
          "「ブラウンさんです」— 人を答えているので正解",
          "「オフィスの中です」— 場所の答え",
          "「月曜日です」— 曜日の答え",
        ],
        answer: 0,
        exp: "Who(誰)と人を聞かれているので、人名を答える (A) が正解です。",
      },
    ],
    part5: [
      {
        q: "Ms. Tanaka ------- a teacher at Greenhill Elementary School.",
        ja: "タナカさんはグリーンヒル小学校の教師です。",
        choices: ["is", "are", "am", "be"],
        choiceNotes: [
          "主語が三人称単数(Ms. Tanaka)なので is が正解",
          "are は主語が you や複数のときに使う",
          "am は主語が I のときだけ",
          "be は原形。will や to の後ろで使う形",
        ],
        answer: 0,
        exp: "主語 Ms. Tanaka は三人称単数なので be動詞は is。be動詞の使い分け(am/is/are)は最重要基礎です。",
      },
      {
        q: "The meeting will start ------- 10:00 A.M.",
        ja: "会議は午前10時に始まります。",
        choices: ["in", "at", "on", "of"],
        choiceNotes: [
          "in は月・年・季節に使う(in May)",
          "at は時刻に使うので正解(at 10:00)",
          "on は日付・曜日に使う(on Monday)",
          "of に時を表す使い方はない",
        ],
        answer: 1,
        exp: "時刻には at を使います(at 10:00)。日付は on、月や年は in です。",
      },
      {
        q: "Please put the boxes ------- the table.",
        ja: "箱をテーブルの上に置いてください。",
        choices: ["on", "at", "to", "with"],
        choiceNotes: [
          "on は接触している「上」を表すので正解",
          "at は地点を表す(at the station)",
          "to は方向「〜へ」",
          "with は「〜と一緒に」",
        ],
        answer: 0,
        exp: "「テーブルの上に」= on the table。on は接触している「上」を表します。",
      },
      {
        q: "Mr. Lee ------- to work by bus every day.",
        ja: "リーさんは毎日バスで通勤しています。",
        choices: ["go", "goes", "going", "to go"],
        choiceNotes: [
          "go のままでは三単現の s が足りない",
          "主語が三人称単数+現在の習慣なので goes が正解",
          "going は be動詞がないと使えない",
          "to go は不定詞。動詞の位置には置けない",
        ],
        answer: 1,
        exp: "主語が三人称単数(Mr. Lee)で現在の習慣なので、動詞に s が付いた goes が正解です。",
      },
      {
        q: "This is ------- office.",
        ja: "ここは私たちのオフィスです。",
        choices: ["we", "us", "our", "ours"],
        choiceNotes: [
          "we は主格「私たちは」",
          "us は目的格「私たちを」",
          "our は所有格。名詞の前に置けるので正解",
          "ours は「私たちのもの」。後ろに名詞を置けない",
        ],
        answer: 2,
        exp: "名詞 office の前に置けるのは所有格の our(私たちの)。ours は後ろに名詞を置けません。",
      },
      {
        q: "The store is open ------- Monday to Friday.",
        ja: "その店は月曜から金曜まで開いています。",
        choices: ["from", "for", "by", "since"],
        choiceNotes: [
          "from A to B「AからBまで」で正解",
          "for は期間の長さ(for two hours)",
          "by は期限「〜までに」",
          "since は起点「〜以来」。完了形と使う",
        ],
        answer: 0,
        exp: "「〜から…まで」は from A to B。from Monday to Friday で「月曜から金曜まで」です。",
      },
      {
        q: "------- you have any questions, please call us.",
        ja: "ご質問があれば、お電話ください。",
        choices: ["If", "So", "But", "Or"],
        choiceNotes: [
          "If「もし〜なら」条件を表すので正解",
          "So「だから」は結果を表す",
          "But「しかし」は逆接",
          "Or「または」は選択",
        ],
        answer: 0,
        exp: "「もし質問があれば」という条件を表すのは If。ビジネスメールの定番表現です。",
      },
      {
        q: "The new computers are very -------.",
        ja: "新しいコンピューターはとても役に立ちます。",
        choices: ["use", "useful", "usefully", "using"],
        choiceNotes: [
          "use は動詞/名詞「使う・使用」",
          "useful は形容詞「役に立つ」。be動詞の後ろに置けるので正解",
          "usefully は副詞「役立つように」",
          "using は動名詞/現在分詞",
        ],
        answer: 1,
        exp: "be動詞の後ろで主語を説明するのは形容詞 useful(役に立つ)。-ful は形容詞を作る語尾です。",
      },
    ],
    part7: {
      title: "お知らせ(NOTICE)",
      ja: "市立図書館が祝日のため5月5日(月)に休館し、5月6日(火)午前9時に再開するというお知らせ。正面入口前の返却ボックスはいつでも利用できる。",
      passage:
        "NOTICE\n\nThe City Library will be closed on Monday, May 5, for a national holiday. It will open again on Tuesday, May 6, at 9:00 A.M.\n\nBooks can be returned at the return box in front of the main door at any time.\n\nThank you,\nCity Library Staff",
      qs: [
        {
          q: "What is the notice mainly about?",
          ja: "このお知らせは主に何についてですか?",
          choices: ["A library closing", "A new book", "A city festival", "A job opening"],
          choiceNotes: [
            "図書館の休館 — 1文目に明記されているので正解",
            "新しい本 — 本文に記述なし",
            "市のお祭り — 祝日とあるが祭りの話はない",
            "求人 — 本文に記述なし",
          ],
          answer: 0,
          exp: "1文目に「図書館は5月5日に閉館します」とあるので、お知らせの主題は図書館の休館です。",
        },
        {
          q: "When will the library open again?",
          ja: "図書館はいつ再開しますか?",
          choices: ["On May 5", "On May 6", "On May 9", "On Monday"],
          choiceNotes: [
            "5月5日は休館日",
            "5月6日(火)に再開と明記されているので正解",
            "5月9日は本文に記述なし",
            "月曜日は休館する曜日",
          ],
          answer: 1,
          exp: "It will open again on Tuesday, May 6 とあるので、再開は5月6日(火)です。",
        },
        {
          q: "What can people do on May 5?",
          ja: "5月5日に人々ができることは何ですか?",
          choices: [
            "Borrow new books",
            "Meet the library staff",
            "Return books at the box",
            "Attend a holiday event",
          ],
          choiceNotes: [
            "本を借りる — 休館中はできない",
            "職員に会う — 休館中はできない",
            "ボックスで返却 — at any time(いつでも)可能なので正解",
            "イベントに参加 — 本文に記述なし",
          ],
          answer: 2,
          exp: "返却ボックスは at any time(いつでも)使えると書かれているので、休館日でも返却は可能です。",
        },
      ],
    },
  },

  // ---------------- Lv2 初級(目標500) ----------------
  2: {
    part2: [
      {
        q: "How do I get to the airport?",
        ja: "空港へはどう行けばいいですか?",
        choices: ["You can take the express train.", "About two hours ago.", "It was very expensive."],
        choiceNotes: [
          "「急行電車が使えますよ」— 手段を答えているので正解",
          "「約2時間前です」— 時の答え",
          "「とても高かったです」— 感想で噛み合わない",
        ],
        answer: 0,
        exp: "How(どうやって)と手段を聞かれているので、交通手段を答える (A) が正解です。",
      },
      {
        q: "Would you like some coffee?",
        ja: "コーヒーはいかがですか?",
        choices: ["Yes, please. With milk.", "No, it's mine.", "He likes tea."],
        choiceNotes: [
          "「はい、お願いします。ミルク入りで」— 申し出を受けており正解",
          "「いいえ、それは私のものです」— mine の音ひっかけ",
          "「彼は紅茶が好きです」— 第三者の話で噛み合わない",
        ],
        answer: 0,
        exp: "Would you like 〜? は「〜はいかがですか」という提案。Yes, please. と受ける (A) が自然です。",
      },
      {
        q: "Why was the meeting canceled?",
        ja: "なぜ会議は中止になったのですか?",
        choices: ["Because the manager is out of town.", "In the conference room.", "Yes, it was."],
        choiceNotes: [
          "「部長が出張中だからです」— 理由を答えているので正解",
          "「会議室でです」— 場所の答え",
          "「はい、そうでした」— Why に Yes/No では答えられない",
        ],
        answer: 0,
        exp: "Why(なぜ)には理由を答えます。Because で理由を述べる (A) が正解。Why に Yes/No では答えられません。",
      },
    ],
    part5: [
      {
        q: "All employees ------- attend the safety training next week.",
        ja: "全従業員は来週、安全研修に参加しなければなりません。",
        choices: ["must", "musts", "musting", "to must"],
        choiceNotes: [
          "must は助動詞で形が変わらない。これが正解",
          "助動詞に s は付かない",
          "助動詞に ing形は存在しない",
          "to の後ろに助動詞は置けない",
        ],
        answer: 0,
        exp: "must(〜しなければならない)は助動詞なので形が変化せず、後ろに動詞の原形が続きます。",
      },
      {
        q: "Ms. Garcia ------- the report yesterday.",
        ja: "ガルシアさんは昨日、報告書を仕上げました。",
        choices: ["finish", "finished", "finishes", "finishing"],
        choiceNotes: [
          "原形は yesterday(過去)と合わない",
          "過去形。yesterday と一致するので正解",
          "現在形(三単現)は過去と合わない",
          "ing形は be動詞が必要",
        ],
        answer: 1,
        exp: "yesterday(昨日)があるので過去形 finished が正解。時を表す語句が時制のヒントになります。",
      },
      {
        q: "The restaurant is famous ------- its fresh seafood.",
        ja: "そのレストランは新鮮な魚介類で有名です。",
        choices: ["for", "to", "at", "in"],
        choiceNotes: [
          "be famous for「〜で有名」の熟語で正解",
          "famous to という形はない",
          "be good at との混同を狙ったひっかけ",
          "be interested in との混同を狙ったひっかけ",
        ],
        answer: 0,
        exp: "be famous for 〜 =「〜で有名だ」。前置詞とセットで覚える定番表現です。",
      },
      {
        q: "Please send the documents ------- Friday.",
        ja: "金曜日までに書類を送ってください。",
        choices: ["by", "until", "at", "in"],
        choiceNotes: [
          "by「〜までに(期限)」で正解",
          "until は「〜までずっと(継続)」。1回の動作 send と合わない",
          "at は時刻に使う",
          "in は月・年に使う",
        ],
        answer: 0,
        exp: "by は「〜までに(期限)」、until は「〜までずっと(継続)」。書類の提出期限なので by が正解です。",
      },
      {
        q: "Mr. Chen is interested ------- the new marketing position.",
        ja: "チェンさんは新しいマーケティング職に興味があります。",
        choices: ["in", "on", "to", "for"],
        choiceNotes: [
          "be interested in「〜に興味がある」で正解",
          "on では熟語にならない",
          "to では熟語にならない",
          "for では熟語にならない",
        ],
        answer: 0,
        exp: "be interested in 〜 =「〜に興味がある」。TOEIC頻出の熟語です。",
      },
      {
        q: "The office will be closed ------- the holiday.",
        ja: "祝日の間、オフィスは閉まります。",
        choices: ["during", "while", "when", "since"],
        choiceNotes: [
          "前置詞 during は名詞(the holiday)を続けられるので正解",
          "while は接続詞。後ろに主語+動詞が必要",
          "when も接続詞。後ろに主語+動詞が必要",
          "since「〜以来」は意味が合わない",
        ],
        answer: 0,
        exp: "空所の後ろが名詞(the holiday)なので前置詞 during が正解。while や when は後ろに主語+動詞が必要です。",
      },
      {
        q: "Employees can choose ------- the morning shift and the evening shift.",
        ja: "従業員は朝のシフトと夜のシフトのどちらかを選べます。",
        choices: ["between", "among", "from", "with"],
        choiceNotes: [
          "between A and B「AとBの間で」で正解",
          "among は3つ以上のときに使う",
          "choose from なら「〜の中から」だが and と合わない",
          "with では意味が通らない",
        ],
        answer: 0,
        exp: "between A and B =「AとBの間で」。2つから選ぶときは between、3つ以上は among です。",
      },
      {
        q: "The elevator is ------- repaired, so please use the stairs.",
        ja: "エレベーターは現在修理中のため、階段をご利用ください。",
        choices: ["being", "been", "be", "is"],
        choiceNotes: [
          "is being repaired「今まさに修理されている」進行形の受動態で正解",
          "been は has been の形で使う",
          "原形 be は is の後ろに置けない",
          "is が二重になってしまう",
        ],
        answer: 0,
        exp: "is being repaired =「現在修理中」(進行形の受動態)。「今まさに〜されている」を表します。",
      },
    ],
    part7: {
      title: "社内メール(E-mail)",
      ja: "今週土曜8時〜正午にオフィスの業者清掃を行うため、金曜夜に私物を持ち帰り、机と棚を空にするよう求める社内メール。土曜午前に仕事をする場合は1階の会議室を使う。",
      passage:
        "From: Kenji Mori, Office Manager\nTo: All Staff\nSubject: Office Cleaning on Saturday\n\nDear Staff,\n\nThe office will be professionally cleaned this Saturday from 8:00 A.M. to noon. Please take all personal items home on Friday evening. Desks and shelves must be completely empty.\n\nIf you need to work on Saturday morning, please use the meeting room on the first floor.\n\nThank you for your cooperation.\n\nKenji Mori",
      qs: [
        {
          q: "Why was the e-mail sent?",
          ja: "このメールはなぜ送られたのですか?",
          choices: [
            "To announce a cleaning schedule",
            "To introduce a new staff member",
            "To change a meeting time",
            "To report a broken elevator",
          ],
          choiceNotes: [
            "清掃予定の告知 — 件名と本文の内容に一致するので正解",
            "新入社員の紹介 — 記述なし",
            "会議時間の変更 — 記述なし",
            "エレベーター故障の報告 — 記述なし",
          ],
          answer: 0,
          exp: "件名と本文から、土曜日のオフィス清掃について知らせるメールだとわかります。",
        },
        {
          q: "What should staff do on Friday?",
          ja: "金曜日に社員は何をすべきですか?",
          choices: [
            "Work in the meeting room",
            "Take personal items home",
            "Clean their own desks",
            "Come to work at 8:00 A.M.",
          ],
          choiceNotes: [
            "会議室で働く — それは土曜日の話",
            "私物を持ち帰る — 本文の指示どおりで正解",
            "自分で机を掃除 — 清掃するのは業者",
            "朝8時に出社 — 記述なし",
          ],
          answer: 1,
          exp: "Please take all personal items home on Friday evening と指示されています。",
        },
        {
          q: "Where can staff work on Saturday morning?",
          ja: "土曜の午前中、社員はどこで働けますか?",
          choices: [
            "At their own desks",
            "In the first-floor meeting room",
            "At home only",
            "In the manager's office",
          ],
          choiceNotes: [
            "自分の机 — 清掃中のため使えない",
            "1階の会議室 — 本文の指示どおりで正解",
            "自宅のみ — 記述なし",
            "部長室 — 記述なし",
          ],
          answer: 1,
          exp: "土曜に働く必要がある人は「1階の会議室を使ってください」と書かれています。",
        },
      ],
    },
  },

  // ---------------- Lv3 中級(目標600) ----------------
  3: {
    part2: [
      {
        q: "Have you finished the sales report yet?",
        ja: "営業報告書はもう仕上がりましたか?",
        choices: [
          "Almost — I just need to add the charts.",
          "Yes, he's on sale.",
          "The store closes at eight.",
        ],
        choiceNotes: [
          "「ほぼ。あとはグラフを足すだけです」— 進捗を答えており正解",
          "「はい、彼は特価中です」— sales と sale の音ひっかけ",
          "「店は8時に閉まります」— 無関係な内容",
        ],
        answer: 0,
        exp: "「もう終わった?」に対して「ほぼ終わった、あとはグラフだけ」と進捗を答える (A) が自然です。",
      },
      {
        q: "Should we take a taxi or the subway?",
        ja: "タクシーと地下鉄、どちらにしましょうか?",
        choices: [
          "The subway would be faster at this hour.",
          "Yes, we should.",
          "I took it yesterday.",
        ],
        choiceNotes: [
          "「この時間なら地下鉄の方が速いですよ」— 一方を選んでおり正解",
          "「はい、そうすべきです」— A or B の選択疑問文に Yes/No は不可",
          "「昨日それに乗りました」— 質問に噛み合わない",
        ],
        answer: 0,
        exp: "A or B の選択疑問文には、どちらかを選んで答えます。Yes/No で答える (B) は不正解です。",
      },
      {
        q: "Who's going to train the new staff?",
        ja: "新人研修は誰が担当するのですか?",
        choices: [
          "Ms. Sato volunteered to do it.",
          "The train leaves at noon.",
          "For about three weeks.",
        ],
        choiceNotes: [
          "「サトウさんが買って出てくれました」— 人を答えており正解",
          "「電車は正午に出ます」— train(訓練する/電車)の多義語ひっかけ",
          "「約3週間です」— 期間の答え。How long ならOK",
        ],
        answer: 0,
        exp: "Who に対して人名で答える (A) が正解。(B)は train(訓練する/電車)の多義語ひっかけです。",
      },
    ],
    part5: [
      {
        q: "The company announced a ------- increase in sales last quarter.",
        ja: "その会社は前四半期、売上の大幅な増加を発表しました。",
        choices: ["signify", "significant", "significantly", "significance"],
        choiceNotes: [
          "signify は動詞「意味する」",
          "significant は形容詞。名詞 increase を修飾できるので正解",
          "significantly は副詞。名詞は修飾できない",
          "significance は名詞。increase と名詞が二重になる",
        ],
        answer: 1,
        exp: "名詞 increase を修飾するのは形容詞 significant(大幅な)。品詞問題は空所の前後だけで解けます。",
      },
      {
        q: "------- the rain, the outdoor event was held as scheduled.",
        ja: "雨にもかかわらず、屋外イベントは予定どおり開催されました。",
        choices: ["Despite", "Although", "However", "Because"],
        choiceNotes: [
          "Despite は前置詞。名詞(the rain)を続けられるので正解",
          "Although は接続詞。後ろに主語+動詞が必要",
          "However は副詞。名詞をつなげない",
          "Because は接続詞で、意味も逆(〜なので)",
        ],
        answer: 0,
        exp: "空所の後ろが名詞(the rain)なので前置詞 Despite(〜にもかかわらず)。Although は後ろに主語+動詞が必要です。",
      },
      {
        q: "Applicants ------- resumes were received by May 1 will be contacted for interviews.",
        ja: "5月1日までに履歴書が届いた応募者には、面接のご連絡をします。",
        choices: ["who", "whose", "which", "whom"],
        choiceNotes: [
          "who の後ろには動詞が続くのが基本形",
          "whose + 名詞で「〜の…が」という所有を表すので正解",
          "which は物を受ける。ここでは所有格が必要",
          "whom は目的格。名詞の前に置けない",
        ],
        answer: 1,
        exp: "「応募者の履歴書」という所有関係なので whose。whose + 名詞 の形で覚えましょう。",
      },
      {
        q: "The manager asked the staff to complete the survey -------.",
        ja: "部長はスタッフにアンケートをすみやかに記入するよう求めました。",
        choices: ["prompt", "promptly", "prompted", "promptness"],
        choiceNotes: [
          "prompt は形容詞/動詞",
          "promptly は副詞。動詞 complete を修飾できるので正解",
          "prompted は過去形/過去分詞",
          "promptness は名詞",
        ],
        answer: 1,
        exp: "動詞 complete を修飾するのは副詞 promptly(すみやかに)。文末の空所は副詞が定番です。",
      },
      {
        q: "Mr. Ito will be transferred to the Osaka branch ------- next month.",
        ja: "イトウさんは来月初めから大阪支社に異動になります。",
        choices: ["begin", "beginning", "begins", "began"],
        choiceNotes: [
          "原形 begin はここに置けない",
          "beginning + 時「〜初めから」の慣用表現で正解(= starting)",
          "begins は三単現だが主語がない",
          "began は過去形。文の動詞が二重になる",
        ],
        answer: 1,
        exp: "beginning next month =「来月初めから」。starting next month と同じく前置詞的に使う頻出表現です。",
      },
      {
        q: "------- of the two proposals was approved by the board.",
        ja: "2つの提案のどちらも、役員会で承認されませんでした。",
        choices: ["Neither", "Both", "Every", "Almost"],
        choiceNotes: [
          "Neither は単数扱い。動詞 was と一致するので正解",
          "Both は複数扱いで were が必要",
          "every of とは言えない(each of ならOK)",
          "Almost は副詞。of の前に置けない",
        ],
        answer: 0,
        exp: "動詞が was(単数)なので、単数扱いの Neither(どちらも〜ない)が正解。Both なら were になります。",
      },
      {
        q: "The seminar has been postponed ------- further notice.",
        ja: "セミナーは追って通知があるまで延期されました。",
        choices: ["until", "by", "to", "in"],
        choiceNotes: [
          "until further notice「追って通知があるまで」の決まり文句で正解",
          "by「〜までに」は期限で、意味が合わない",
          "postpone to なら後ろは具体的な日付",
          "in では意味が成立しない",
        ],
        answer: 0,
        exp: "until further notice =「追って通知があるまで」。TOEIC超頻出の決まり文句です。",
      },
      {
        q: "Employees are encouraged ------- the online training course by the end of the month.",
        ja: "従業員は月末までにオンライン研修を修了するよう奨励されています。",
        choices: ["complete", "completing", "to complete", "completed"],
        choiceNotes: [
          "原形だけでは encouraged とつながらない",
          "encourage は動名詞を取らない",
          "be encouraged to do「〜するよう奨励される」で正解",
          "過去分詞では意味が通らない",
        ],
        answer: 2,
        exp: "be encouraged to do =「〜するよう奨励される」。encourage + 人 + to do の受動態です。",
      },
    ],
    part7: {
      title: "広告(Advertisement)",
      ja: "リバーサイド・フィットネスセンターの新規開業広告。4月入会は登録料無料。25mプール・50台超のマシン・有資格インストラクターのクラスを完備し、毎日6時〜23時営業。先着100名の新規会員にパーソナルトレーナー1時間無料の特典。",
      passage:
        "GRAND OPENING — RIVERSIDE FITNESS CENTER\n\nJoin in April and pay no registration fee!\n\nOur brand-new facility features a 25-meter swimming pool, over 50 exercise machines, and group classes led by certified instructors. We are open daily from 6:00 A.M. to 11:00 P.M.\n\nIn addition, the first 100 new members will receive a free one-hour session with a personal trainer.\n\nVisit www.riversidefit.com or call 555-0142 for details.",
      qs: [
        {
          q: "What is being advertised?",
          ja: "何が宣伝されていますか?",
          choices: ["A fitness center", "A swimming competition", "A cooking class", "A job opening for trainers"],
          choiceNotes: [
            "フィットネスセンター — 見出しのとおりで正解",
            "水泳大会 — プールはあるが大会の話ではない",
            "料理教室 — 記述なし",
            "トレーナーの求人 — 募集ではなく特典の話",
          ],
          answer: 0,
          exp: "見出しに Riverside Fitness Center の GRAND OPENING(新規オープン)とあります。",
        },
        {
          q: "What benefit is offered to people who join in April?",
          ja: "4月に入会する人にはどんな特典がありますか?",
          choices: [
            "A free swimming lesson",
            "No registration fee",
            "A discount on sportswear",
            "Extended opening hours",
          ],
          choiceNotes: [
            "無料水泳レッスン — 記述なし",
            "登録料無料 — pay no registration fee とあり正解",
            "スポーツウェア割引 — 記述なし",
            "営業時間延長 — 記述なし",
          ],
          answer: 1,
          exp: "Join in April and pay no registration fee! =「4月入会なら登録料無料」です。",
        },
        {
          q: "What is indicated about the personal trainer session?",
          ja: "パーソナルトレーナーのセッションについて何が示されていますか?",
          choices: [
            "It costs 100 dollars.",
            "It is available every day.",
            "It is limited to the first 100 members.",
            "It lasts two hours.",
          ],
          choiceNotes: [
            "100ドルかかる — 無料(free)と書かれている",
            "毎日利用可能 — 記述なし",
            "先着100名限定 — the first 100 new members とあり正解",
            "2時間 — 1時間(one-hour)と書かれている",
          ],
          answer: 2,
          exp: "the first 100 new members will receive... =「先着100名の新規会員」限定の特典です。",
        },
      ],
    },
  },

  // ---------------- Lv4 中上級(目標730) ----------------
  4: {
    part2: [
      {
        q: "The printer on the third floor isn't working again.",
        ja: "3階のプリンターがまた動かなくなっています。",
        choices: [
          "I'll call the technician right away.",
          "Print ten copies, please.",
          "Yes, he's working on the project.",
        ],
        choiceNotes: [
          "「すぐに技術者を呼びます」— 問題報告への対応策で正解",
          "「10部印刷してください」— print の連想ひっかけ",
          "「はい、彼はプロジェクトに取り組んでいます」— working の多義語ひっかけ",
        ],
        answer: 0,
        exp: "疑問文ではなく「問題の報告」。それに対して対応策を答える (A) が自然です。平叙文への応答はPart 2の難所です。",
      },
      {
        q: "Didn't you attend the budget meeting yesterday?",
        ja: "昨日の予算会議に出席しなかったのですか?",
        choices: [
          "No, I had a client appointment.",
          "The budget is fine.",
          "Yes, tomorrow at ten.",
        ],
        choiceNotes: [
          "「ええ(出席していません)、顧客との約束があったので」— 否定+理由で正解",
          "「予算は問題ありません」— budget の連想ひっかけ",
          "「はい、明日10時に」— yesterday と時制が矛盾",
        ],
        answer: 0,
        exp: "否定疑問文「出席しなかったの?」に対し、No(出席しなかった)+理由を述べる (A) が正解です。",
      },
      {
        q: "Where should we hold the year-end reception?",
        ja: "年末のレセプションはどこで開きましょうか?",
        choices: [
          "How about the hotel near headquarters?",
          "At the end of the year.",
          "It was well attended.",
        ],
        choiceNotes: [
          "「本社近くのホテルはどうですか?」— 場所の提案で正解",
          "「年末にです」— 場所ではなく時の答え",
          "「盛況でした」— 過去の感想で噛み合わない",
        ],
        answer: 0,
        exp: "場所の相談に、提案(How about 〜?)で返す (A) が自然。質問に質問で返すパターンも正解になり得ます。",
      },
    ],
    part5: [
      {
        q: "Had the shipment arrived on time, the project ------- completed by now.",
        ja: "もし荷物が時間どおりに届いていたら、プロジェクトは今頃完了していたでしょう。",
        choices: ["would have been", "will be", "was", "has been"],
        choiceNotes: [
          "仮定法過去完了の帰結節 would have been で正解",
          "will be は直説法。仮定法の文と合わない",
          "was は単なる過去で、仮定の意味が出ない",
          "has been は現在完了。Had の倒置と呼応しない",
        ],
        answer: 0,
        exp: "If が省略され倒置になった仮定法過去完了(= If the shipment had arrived)。帰結節は would have been です。",
      },
      {
        q: "------- attending the conference, Ms. Park visited several clients in Boston.",
        ja: "会議への出席に加えて、パクさんはボストンで数社の顧客を訪問しました。",
        choices: ["In addition to", "Moreover", "Furthermore", "Additionally"],
        choiceNotes: [
          "In addition to は前置詞句。動名詞を続けられるので正解",
          "Moreover は副詞。名詞をつなげない",
          "Furthermore も副詞",
          "Additionally も副詞",
        ],
        answer: 0,
        exp: "空所の後ろが動名詞(attending)なので前置詞句 In addition to が正解。他の3つは副詞で、名詞をつなげません。",
      },
      {
        q: "The new policy applies to all employees, ------- of their length of service.",
        ja: "新方針は、勤続年数に関係なく全従業員に適用されます。",
        choices: ["regardless", "despite", "instead", "because"],
        choiceNotes: [
          "regardless of「〜に関係なく」で正解",
          "despite は単独で前置詞。of を取らない",
          "instead of「〜の代わりに」は意味が合わない",
          "because of「〜のため」は理由で、文意に合わない",
        ],
        answer: 0,
        exp: "regardless of 〜 =「〜に関係なく」。TOEIC最頻出の熟語の一つです。",
      },
      {
        q: "------- the merger is finalized, the two companies will operate under a single brand name.",
        ja: "合併がひとたび成立すれば、両社は単一のブランド名で営業します。",
        choices: ["Once", "Despite", "During", "Regarding"],
        choiceNotes: [
          "Once は接続詞「いったん〜すれば」。S+Vを続けられるので正解",
          "Despite は前置詞。S+Vを取れない",
          "During も前置詞",
          "Regarding も前置詞「〜に関して」",
        ],
        answer: 0,
        exp: "後ろに主語+動詞が続くので接続詞が必要。Once =「いったん〜すれば」が文意に合います。他の3つは前置詞です。",
      },
      {
        q: "The committee members remained ------- about the proposed budget cuts.",
        ja: "委員会のメンバーは、提案された予算削減について意見が割れたままでした。",
        choices: ["division", "divided", "dividing", "divide"],
        choiceNotes: [
          "division は名詞。remain の補語には形容詞が自然",
          "divided「意見が分かれた」。remain + 形容詞で正解",
          "dividing「分割している」では意味が不自然",
          "divide は動詞の原形",
        ],
        answer: 1,
        exp: "remain + 形容詞 =「〜のままである」。divided(意見が分かれた)が正解。remained divided は頻出コロケーションです。",
      },
      {
        q: "All visitors must obtain a security pass ------- entering the laboratory.",
        ja: "来訪者は全員、実験室に入る前にセキュリティパスを取得しなければなりません。",
        choices: ["prior to", "formerly", "previously", "in advance"],
        choiceNotes: [
          "prior to 〜ing「〜する前に」。動名詞を続けられるので正解",
          "formerly は副詞「以前は」。名詞を取れない",
          "previously も副詞",
          "in advance も副詞句。後ろに名詞を取れない",
        ],
        answer: 0,
        exp: "prior to 〜ing =「〜する前に」(= before)。formerly / previously / in advance は副詞で、後ろに名詞を取れません。",
      },
      {
        q: "The quarterly report contains a ------- analysis of consumer spending trends.",
        ja: "四半期報告書には、消費支出動向の包括的な分析が含まれています。",
        choices: ["comprehend", "comprehensive", "comprehension", "comprehensively"],
        choiceNotes: [
          "comprehend は動詞「理解する」",
          "comprehensive は形容詞。名詞 analysis を修飾するので正解",
          "comprehension は名詞「理解」",
          "comprehensively は副詞",
        ],
        answer: 1,
        exp: "名詞 analysis を修飾する形容詞 comprehensive(包括的な)が正解。a comprehensive analysis は定番の組み合わせです。",
      },
      {
        q: "Ms. Alvarez handled the difficult negotiation -------.",
        ja: "アルバレスさんは難しい交渉を巧みに処理しました。",
        choices: ["skill", "skillful", "skillfully", "skilled"],
        choiceNotes: [
          "skill は名詞",
          "skillful は形容詞。修飾する名詞がここにはない",
          "skillfully は副詞。動詞 handled を修飾するので正解",
          "skilled は形容詞「熟練した」。人などを修飾する",
        ],
        answer: 2,
        exp: "動詞 handled を修飾するのは副詞 skillfully(巧みに)。「動詞+目的語」の後ろの空所は副詞が基本です。",
      },
    ],
    part7: {
      title: "社内連絡(Memo)",
      ja: "7月1日より、3日を超える出張は2週間前までに事業部長の承認が必要になるという人事部の通達。航空券は指定代理店 GlobalGo Travel 経由でないと払い戻し不可。領収書は出張後30日以内に提出する必要がある。",
      passage:
        "To: All Department Heads\nFrom: Human Resources\nRe: Updated Travel Policy\n\nEffective July 1, all business trips exceeding three days must be approved by a division director at least two weeks in advance.\n\nEmployees are also reminded to book flights through the company's designated agency, GlobalGo Travel, in order to qualify for reimbursement. Receipts submitted later than 30 days after the trip will no longer be accepted.\n\nQuestions may be directed to the HR service desk at extension 2200.",
      qs: [
        {
          q: "What is the main purpose of the memo?",
          ja: "この連絡の主な目的は何ですか?",
          choices: [
            "To announce changes to travel rules",
            "To introduce a new travel agency",
            "To report on a recent business trip",
            "To request budget estimates",
          ],
          choiceNotes: [
            "出張規定の変更告知 — 件名 Updated Travel Policy と一致し正解",
            "旅行代理店の紹介 — 言及はあるが主目的ではない",
            "最近の出張報告 — 記述なし",
            "予算見積もりの依頼 — 記述なし",
          ],
          answer: 0,
          exp: "件名の Updated Travel Policy と本文全体から、出張規定の変更を知らせるのが目的です。",
        },
        {
          q: "What must employees do to be reimbursed for flights?",
          ja: "航空券の払い戻しを受けるには、従業員は何をしなければなりませんか?",
          choices: [
            "Get approval from HR",
            "Book through GlobalGo Travel",
            "Pay with a company credit card",
            "Travel for fewer than three days",
          ],
          choiceNotes: [
            "人事部の承認 — 承認するのは事業部長で、対象も出張自体",
            "GlobalGo Travel で予約 — 本文の条件どおりで正解",
            "会社のカードで支払う — 記述なし",
            "3日未満の出張にする — 記述なし",
          ],
          answer: 1,
          exp: "「払い戻しの対象になるには指定代理店 GlobalGo Travel で予約を」と書かれています。",
        },
        {
          q: "What is indicated about receipts?",
          ja: "領収書について何が示されていますか?",
          choices: [
            "They must be submitted within 30 days.",
            "They should be sent to a division director.",
            "They are no longer required.",
            "They must be printed in color.",
          ],
          choiceNotes: [
            "30日以内に提出 —「30日を過ぎたら受理しない」の言い換えで正解",
            "事業部長に送る — 提出先の記述はない",
            "もう不要 — 逆の内容",
            "カラー印刷が必要 — 記述なし",
          ],
          answer: 0,
          exp: "「出張後30日を過ぎて提出された領収書は受け付けない」=30日以内の提出が必要、と言い換えられます。",
        },
      ],
    },
  },

  // ---------------- Lv5 上級(目標860) ----------------
  5: {
    part2: [
      {
        q: "Why don't we outsource the payroll processing?",
        ja: "給与計算の処理を外注してはどうでしょう?",
        choices: [
          "That could save us quite a bit of time.",
          "The salary was processed yesterday.",
          "Because it's outside the office.",
        ],
        choiceNotes: [
          "「かなりの時間の節約になりそうですね」— 提案への賛同で正解",
          "「給与は昨日処理されました」— salary/processing の連想ひっかけ",
          "「オフィスの外にあるからです」— outsource → outside の音ひっかけ。Why don't we は理由を聞いていない",
        ],
        answer: 0,
        exp: "Why don't we 〜? は理由を聞く疑問文ではなく「〜しませんか」という提案。賛意を示す (A) が正解です。",
      },
      {
        q: "Who's supposed to sign off on these invoices?",
        ja: "これらの請求書は誰が承認することになっていますか?",
        choices: [
          "That would be the accounting director.",
          "The sign is over there by the entrance.",
          "By the end of the week, ideally.",
        ],
        choiceNotes: [
          "「経理部長のはずです」— 人を答えており正解",
          "「看板は入口のそばです」— sign の多義語ひっかけ",
          "「できれば週末までに」— 期限の答え。When ならOK",
        ],
        answer: 0,
        exp: "sign off on 〜 =「〜を承認する」。承認者(人)を答える (A) が正解。(B)は sign の音のひっかけです。",
      },
      {
        q: "The client wants to move the deadline up a week.",
        ja: "クライアントが納期を1週間前倒ししたいそうです。",
        choices: [
          "Then we'll need to bring in extra staff.",
          "The client moved to a new office last week.",
          "It's up on the top shelf.",
        ],
        choiceNotes: [
          "「では応援のスタッフを入れる必要がありますね」— 対応策で正解",
          "「クライアントは先週引っ越しました」— moved の多義語ひっかけ",
          "「上の棚にありますよ」— up の音ひっかけ",
        ],
        answer: 0,
        exp: "move up =「(予定を)前倒しする」。納期短縮の報告に対し、対応策を述べる (A) が自然です。",
      },
    ],
    part5: [
      {
        q: "The board voted to ------- the merger agreement, citing concerns over regulatory approval.",
        ja: "取締役会は、規制当局の承認への懸念を理由に、合併契約を撤回することを票決しました。",
        choices: ["rescind", "reside", "resume", "restore"],
        choiceNotes: [
          "rescind「(契約・決定を)撤回する」で正解",
          "reside は「居住する」",
          "resume は「再開する」",
          "restore は「復元する」",
        ],
        answer: 0,
        exp: "rescind =「(契約・決定を)撤回する」。900点レベルの重要語。citing concerns(懸念を理由に挙げて)も頻出表現です。",
      },
      {
        q: "------- had the CEO finished speaking when reporters began asking questions.",
        ja: "CEOが話し終えるやいなや、記者たちが質問を始めました。",
        choices: ["Scarcely", "Rarely", "Seldom", "Never"],
        choiceNotes: [
          "Scarcely had S done ... when 〜「〜するやいなや」の構文で正解",
          "Rarely「めったに〜ない」は when と呼応しない",
          "Seldom も頻度の副詞で when と呼応しない",
          "Never はこの構文を作らない",
        ],
        answer: 0,
        exp: "Scarcely had S done ... when 〜 =「〜するやいなや…」の倒置構文。when と呼応するのは Scarcely / Hardly です。",
      },
      {
        q: "The auditor found several ------- in the company's financial statements.",
        ja: "監査人は、会社の財務諸表にいくつかの不一致を発見しました。",
        choices: ["discrepancies", "discretions", "descriptions", "distractions"],
        choiceNotes: [
          "discrepancy「(数字の)食い違い・不一致」で正解",
          "discretion は「裁量・思慮」",
          "description は「記述・説明」",
          "distraction は「気を散らすもの」",
        ],
        answer: 0,
        exp: "discrepancy =「(数字などの)食い違い、不一致」。監査(auditor)の文脈で頻出。似た綴りの語に注意。",
      },
      {
        q: "Sales of the new device have exceeded expectations, ------- analysts to revise their forecasts upward.",
        ja: "新型デバイスの売上は予想を上回り、アナリストに予測の上方修正を促しました。",
        choices: ["prompting", "prompted", "prompt", "prompts"],
        choiceNotes: [
          "現在分詞の分詞構文(能動「〜を促して」)で正解",
          "過去分詞だと受動の意味になり不自然",
          "原形はここに置けない",
          "三単現は接続詞がないため置けない",
        ],
        answer: 0,
        exp: "「, ------- 〜」は分詞構文。「売上が予想を超え、その結果アナリストに予測の上方修正を促した」という能動の関係なので現在分詞 prompting です。",
      },
      {
        q: "The proposed regulations, ------- adopted, would significantly affect small businesses.",
        ja: "提案されている規制は、もし採択されれば、中小企業に大きな影響を与えるでしょう。",
        choices: ["if", "unless", "whereas", "despite"],
        choiceNotes: [
          "if (they are) adopted の省略形で正解",
          "unless「〜でない限り」では主節と意味が矛盾する",
          "whereas「一方で」はこの省略構文を作らない",
          "despite は前置詞。過去分詞と直接つながらない",
        ],
        answer: 0,
        exp: "if adopted = if they are adopted の省略形。「もし採択されれば」。挿入された if + 過去分詞のパターンです。",
      },
      {
        q: "Employees who work remotely must ensure that confidential documents are stored in a ------- manner.",
        ja: "在宅勤務の従業員は、機密書類が安全な方法で保管されるようにしなければなりません。",
        choices: ["secure", "securely", "security", "secured"],
        choiceNotes: [
          "形容詞 secure が名詞 manner を修飾。in a secure manner で正解",
          "securely は副詞。名詞を修飾できない",
          "security は名詞。manner と二重になる",
          "secured「確保された」は manner の修飾に不自然",
        ],
        answer: 0,
        exp: "in a ------- manner の空所には名詞 manner を修飾する形容詞 secure が入ります。in a secure manner =「安全な方法で」。",
      },
      {
        q: "The keynote speaker's remarks were both insightful and -------.",
        ja: "基調講演者の発言は、洞察に富み、かつ考えさせられるものでした。",
        choices: ["thought-provoking", "provoke", "provocation", "provokes"],
        choiceNotes: [
          "形容詞 thought-provoking。insightful と並列になるので正解",
          "provoke は動詞。並列が崩れる",
          "provocation は名詞",
          "provokes は動詞の三単現",
        ],
        answer: 0,
        exp: "both A and B のAが形容詞(insightful)なので、Bも形容詞 thought-provoking(考えさせられる)。並列構造は同じ品詞で揃えます。",
      },
      {
        q: "------- to popular belief, the company's founder did not start the business in a garage.",
        ja: "一般に信じられているのとは違い、創業者はガレージで事業を始めたわけではありません。",
        choices: ["Contrary", "Opposite", "Against", "Unlike"],
        choiceNotes: [
          "contrary to popular belief の決まり文句で正解",
          "opposite to は位置関係「〜の向かい」",
          "against はこの形の慣用表現を作らない",
          "unlike は後ろに直接名詞を取り、to が不要",
        ],
        answer: 0,
        exp: "contrary to popular belief =「一般に信じられているのとは違って」。決まり文句として丸ごと覚えましょう。",
      },
    ],
    part7: {
      title: "ビジネス記事(Article)",
      ja: "食品会社ハーロウ・フーズが飲料会社デルタ・ビバレッジを3億4,000万ドルで買収すると発表した記事。狙いは東南アジアの流通網で、規制承認を経て第4四半期に完了見込み。株価は4%上昇したが、統合には想定より時間がかかるという慎重な見方もある。",
      passage:
        "HARLOW FOODS TO ACQUIRE DELTA BEVERAGE\n\nHarlow Foods announced on Tuesday that it will acquire Delta Beverage for $340 million, a move analysts say will strengthen its position in the fast-growing functional-drinks market.\n\nThe acquisition, expected to close in the fourth quarter pending regulatory approval, would give Harlow access to Delta's extensive distribution network across Southeast Asia. \"This is less about adding products and more about reach,\" said CEO Marta Villanueva.\n\nHarlow shares rose 4 percent on the news. Some industry observers, however, cautioned that integrating the two companies' operations could take longer than projected.",
      qs: [
        {
          q: "What is the article mainly about?",
          ja: "この記事は主に何についてですか?",
          choices: [
            "A planned acquisition",
            "A new product launch",
            "A change in company leadership",
            "A drop in share prices",
          ],
          choiceNotes: [
            "買収計画 — 見出し・第1段落のとおりで正解",
            "新製品発売 — 記述なし",
            "経営陣の交代 — 記述なし",
            "株価下落 — 実際は4%上昇している",
          ],
          answer: 0,
          exp: "見出しと第1段落から、Harlow Foods による Delta Beverage の買収計画が主題です。",
        },
        {
          q: "According to Ms. Villanueva, what is the main benefit of the deal?",
          ja: "ビジャヌエバCEOによれば、この取引の主な利点は何ですか?",
          choices: [
            "Expanded distribution reach",
            "A larger product lineup",
            "Lower production costs",
            "Faster regulatory approval",
          ],
          choiceNotes: [
            "流通網の拡大 —「reach(届く範囲)が目的」という発言と一致し正解",
            "製品ラインの拡大 —「製品追加が目的ではない」と明言している",
            "生産コスト低減 — 記述なし",
            "規制承認の迅速化 — 記述なし",
          ],
          answer: 0,
          exp: "「製品を増やすことより reach(販路・届く範囲)が目的だ」という発言と、東南アジアの流通網への言及が根拠です。",
        },
        {
          q: "What concern is mentioned in the article?",
          ja: "記事の中で言及されている懸念は何ですか?",
          choices: [
            "Integration may take longer than expected.",
            "The purchase price is too high.",
            "Consumer demand is declining.",
            "Regulators have rejected the deal.",
          ],
          choiceNotes: [
            "統合に想定以上の時間 — 最終段落の警告どおりで正解",
            "買収価格が高すぎる — 記述なし",
            "消費者需要の減少 — むしろ急成長市場と書かれている",
            "当局が却下した — まだ承認待ちの段階",
          ],
          answer: 0,
          exp: "最終段落で「両社の統合は予定より時間がかかる可能性がある」と業界関係者が警告しています。",
        },
      ],
    },
  },

  // ---------------- Lv6 最上級(目標950) ----------------
  6: {
    part2: [
      {
        q: "Weren't the quarterly figures supposed to be released this morning?",
        ja: "四半期決算は今朝発表されるはずではなかったのですか?",
        choices: [
          "They've been held back pending an audit.",
          "Yes, every quarter has four months.",
          "The morning shift starts at six.",
        ],
        choiceNotes: [
          "「監査待ちで公表が見送られています」— 状況を説明しており正解",
          "「はい、四半期は4カ月ごとです」— quarter の単語ひっかけで内容も誤り",
          "「早番は6時開始です」— morning の音ひっかけ",
        ],
        answer: 0,
        exp: "hold back =「公表を見送る」、pending =「〜を待つ間」。直接 Yes/No で答えず状況を説明する、最難関の応答パターンです。",
      },
      {
        q: "How did the investors react to the restructuring plan?",
        ja: "投資家は再建計画にどのような反応を示しましたか?",
        choices: [
          "More favorably than we'd anticipated.",
          "They arrived at the plant this morning.",
          "The structure is quite old, actually.",
        ],
        choiceNotes: [
          "「予想以上に好意的でした」— 反応を答えており正解",
          "「彼らは今朝工場に到着しました」— 無関係な内容",
          "「その建物はかなり古いですね」— restructuring → structure の音ひっかけ",
        ],
        answer: 0,
        exp: "反応を聞かれて「予想以上に好意的だった」と比較級で答える (A) が正解。(C)は restructuring と structure の音のひっかけです。",
      },
      {
        q: "Shall I forward the revised contract to the legal team, or would you rather review it first?",
        ja: "修正版の契約書を法務チームに転送しましょうか、それとも先にご確認されますか?",
        choices: [
          "Let me take one more look before it goes out.",
          "The contract was signed last year.",
          "Yes, I would.",
        ],
        choiceNotes: [
          "「送る前にもう一度確認させてください」— 後者を選んでおり正解",
          "「契約は昨年締結されました」— contract の連想ひっかけ",
          "「はい、そうします」— 選択疑問文に Yes では答えられない",
        ],
        answer: 0,
        exp: "選択疑問文。「送る前にもう一度見せて」=後者(自分が先に確認する)を選んだ (A) が正解。(C)のように Yes では答えられません。",
      },
    ],
    part5: [
      {
        q: "The two firms reached a(n) ------- agreement after months of contentious negotiations.",
        ja: "両社は数カ月に及ぶ激しい交渉の末、友好的な合意に達しました。",
        choices: ["amicable", "ambiguous", "adamant", "arbitrary"],
        choiceNotes: [
          "amicable「友好的な」。contentious(争いの多い)との対比で正解",
          "ambiguous は「曖昧な」",
          "adamant は「断固とした」。人の態度に使う",
          "arbitrary は「恣意的な」",
        ],
        answer: 0,
        exp: "amicable =「友好的な」。contentious(争いの多い)交渉の末に達した合意、という対比が決め手です。",
      },
      {
        q: "Not until the final quarter ------- signs of recovery.",
        ja: "最終四半期になって初めて、市場は回復の兆しを見せました。",
        choices: ["did the market show", "the market showed", "showed the market", "the market did show"],
        choiceNotes: [
          "Not until が文頭 → 主節は疑問文の語順に倒置。これが正解",
          "倒置していないので誤り",
          "動詞が先頭に来る形は誤り。did による倒置が必要",
          "did の位置が誤り(主語の前に出る)",
        ],
        answer: 0,
        exp: "Not until 〜 が文頭に出ると主節は倒置(疑問文の語順)になります。Not until X did S V が定型です。",
      },
      {
        q: "The consultant's recommendations were largely ------- with the findings of the internal review.",
        ja: "コンサルタントの提言は、内部調査の結果とおおむね一致していました。",
        choices: ["consistent", "consisting", "consisted", "consistency"],
        choiceNotes: [
          "be consistent with「〜と一致している」で正解",
          "consist of「〜から成る」との混同を狙ったひっかけ",
          "過去形は were と二重になる",
          "consistency は名詞",
        ],
        answer: 0,
        exp: "be consistent with 〜 =「〜と一致している」。consist of(〜から成る)との混同を狙った問題です。",
      },
      {
        q: "The CFO cautioned that the projections were ------- at best, given the volatile exchange rates.",
        ja: "CFOは、為替相場が不安定なため、この予測はよくても暫定的なものだと注意を促しました。",
        choices: ["tentative", "tenacious", "tangible", "temperate"],
        choiceNotes: [
          "tentative「暫定的な」。at best(よくても)と合い正解",
          "tenacious は「粘り強い」",
          "tangible は「有形の・具体的な」",
          "temperate は「温暖な・節度のある」",
        ],
        answer: 0,
        exp: "tentative =「暫定的な、仮の」。at best(よくても)と合わせて「よくても暫定値」。紛らわしい t- 語彙の識別問題です。",
      },
      {
        q: "------- the committee approve the amendment, it will take effect immediately.",
        ja: "万一委員会が修正案を承認すれば、それは直ちに発効します。",
        choices: ["Should", "Would", "Could", "Might"],
        choiceNotes: [
          "Should S do = If S should do「万一〜すれば」の倒置で正解",
          "Would はこの倒置構文を作らない",
          "Could も作らない",
          "Might も作らない",
        ],
        answer: 0,
        exp: "Should S do 〜 = If S should do 〜(万一〜すれば)の倒置。文頭の Should は仮定法の目印です。",
      },
      {
        q: "The artisan workshop prides itself ------- using traditional techniques passed down for generations.",
        ja: "その工房は、何世代にもわたって受け継がれた伝統技法を使うことを誇りにしています。",
        choices: ["on", "in", "for", "about"],
        choiceNotes: [
          "pride oneself on「〜を誇りにする」で正解",
          "take pride in との混同を狙ったひっかけ",
          "be famous for との混同を狙ったひっかけ",
          "about では熟語にならない",
        ],
        answer: 0,
        exp: "pride oneself on 〜 =「〜を誇りにする」。= take pride in / be proud of。前置詞の違いに注意。",
      },
      {
        q: "The report attributes the decline in sales ------- shifting consumer preferences.",
        ja: "報告書は、売上減少の原因を消費者の嗜好の変化にあるとしています。",
        choices: ["to", "with", "for", "at"],
        choiceNotes: [
          "attribute A to B「AをBのせいと考える」で正解",
          "credit A with との混同を狙ったひっかけ",
          "blame A for との混同を狙ったひっかけ",
          "at にこの用法はない",
        ],
        answer: 0,
        exp: "attribute A to B =「AをBのせい・おかげと考える」。原因を表す to は必ず押さえたい語法です。",
      },
      {
        q: "Rarely ------- such a comprehensive proposal from a first-year associate.",
        ja: "1年目の社員からこれほど包括的な提案を受け取ることは、めったにありません。",
        choices: ["have we received", "we have received", "we received", "received we"],
        choiceNotes: [
          "否定の副詞 Rarely が文頭 → 倒置語順で正解",
          "倒置していないので誤り",
          "倒置しておらず時制の含みも弱い",
          "英語にこの語順はない",
        ],
        answer: 0,
        exp: "否定の副詞 Rarely が文頭に来ると倒置が起こります。Rarely have we received 〜 =「めったに受け取ったことがない」。",
      },
    ],
    part7: {
      title: "取引先への返信メール(E-mail)",
      ja: "デザインソフトの大口ライセンスに関する問い合わせへの返信メール。標準エンタープライズプランは250シートまでで、先方の希望(3拠点で約400シート)は上限を超えるため個別交渉になる。数量割引が四半期末に失効するため、その前の商談を提案。評価用に試用期間を30日延長した。",
      passage:
        "Dear Mr. Okafor,\n\nThank you for your inquiry regarding bulk licensing of our design software. While our standard enterprise tier covers up to 250 seats, arrangements beyond that threshold are negotiated individually, with pricing dependent on deployment scope and support requirements.\n\nGiven that your firm anticipates rolling out roughly 400 seats across three regional offices, I would suggest scheduling a call with our enterprise sales team before the end of the quarter, when our current volume incentives are due to expire.\n\nIn the meantime, I have extended your trial period by 30 days so that your engineers can complete their evaluation.\n\nBest regards,\nLena Fischer\nAccount Manager, Vectorline Software",
      qs: [
        {
          q: "Why did Ms. Fischer write to Mr. Okafor?",
          ja: "フィッシャーさんがオカフォーさんにメールを書いた理由は何ですか?",
          choices: [
            "To respond to a question about licensing",
            "To announce a new software product",
            "To request payment for an invoice",
            "To schedule a job interview",
          ],
          choiceNotes: [
            "ライセンスに関する質問への返答 — 冒頭の文と一致し正解",
            "新製品の発表 — 記述なし",
            "請求書の支払い依頼 — 記述なし",
            "面接の日程調整 — 記述なし",
          ],
          answer: 0,
          exp: "冒頭の Thank you for your inquiry regarding bulk licensing から、ライセンスに関する問い合わせへの返信だとわかります。",
        },
        {
          q: "What is suggested about Mr. Okafor's firm?",
          ja: "オカフォーさんの会社について何が示唆されていますか?",
          choices: [
            "Its needs exceed the standard enterprise tier.",
            "It has already purchased 250 licenses.",
            "It is opening a fourth regional office.",
            "It develops design software.",
          ],
          choiceNotes: [
            "必要数が標準プランの上限を超える — 400シート > 250シートの推論で正解",
            "既に250ライセンス購入済み — 記述なし",
            "4つ目の拠点を開設 — 3拠点としか書かれていない",
            "デザインソフトを開発 — 開発元は Vectorline 側",
          ],
          answer: 0,
          exp: "標準プランは250シートまで、先方の予定は約400シート。つまり標準プランの上限を超える、という推論(inference)問題です。",
        },
        {
          q: "Why does Ms. Fischer recommend calling before the end of the quarter?",
          ja: "フィッシャーさんが四半期末までの電話を勧めるのはなぜですか?",
          choices: [
            "Volume discounts will expire after that.",
            "The sales team will be reorganized.",
            "The trial period ends then.",
            "Prices will be announced then.",
          ],
          choiceNotes: [
            "数量割引がその後失効するから — incentives are due to expire と一致し正解",
            "営業チームの再編 — 記述なし",
            "試用期間がその時終わる — 試用期間は30日延長済み",
            "価格がその時発表される — 記述なし",
          ],
          answer: 0,
          exp: "when our current volume incentives are due to expire =「現行の大口割引が期限を迎える」ため、その前の相談を勧めています。",
        },
      ],
    },
  },
};
